title: Spirit of Grit Wiki
description: A wiki for the Spirit of Grit modlist
theme: just-the-docs
color_scheme: dark
logo: "/img/SpiritFinal2.png"

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

url: aeloverim.github.io/SpiritOfGrit
